site_name: normalMagic
site_url: https://spaghetmenot.github.io/normalmagic/

theme:
  name: material
  font:
    text: Ubuntu
    code: Red Hat Mono
  logo: assets\normalMagicIcon.png
  favicon: assets\normalMagicIcon.png
  features:
    - navigation.tracking
    - navigation.indexes
    - navigation.sections
    # - navigation.tabs
    
    # - navigation.top
    - toc.follow


  palette:  
  # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: black
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

markdown_extensions:
  - tables
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.keys
  - toc:
      permalink: true

extra:
  # social:
  #   - icon: simple/bluesky
  #     link: https://bsky.app/profile/spaghetmenot.bsky.social
  #   - icon: simple/mastodon
  #     link: https://mastodon.social/@SpaghetMeNot
  #   - icon: simple/x
  #     link: https://x.com/SpaghetMeN0t
  #   - icon: simple/youtube
  #     link: https://www.youtube.com/@SpaghetMeNot
  generator: false


plugins:
  - search
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: auto
      height: auto
      zoomable: true
      draggable: true
      auto_caption: false
      caption_position: bottom
      background: black
      shadow: true
      manual: false

nav:
  - Home: index.md
  - Install: install.md
  - Tools Overview: tools_overview.md
  - Examples: examples.md

  - Mesh Modifiers:
    - mesh_tools/index.md
    - mesh_tools/boolean_pro.md
    - mesh_tools/surface_blend.md
    - mesh_tools/surface_insert.md
  
  - Normal Modifiers:
    - normal_tools/index.md
    - normal_tools/normal_transfer.md
    - normal_tools/smooth_normals.md
    - normal_tools/weighted_normals.md
    - normal_tools/bent_normals.md
    - normal_tools/repair_bevel_normals.md
    - normal_tools/repair_boolean_normals.md
    - normal_tools/repair_mirrored_normals.md

  - Visualize Modifiers:
    - visualize_tools/index.md
    - visualize_tools/view_normals.md
    - visualize_tools/view_sharp.md

  - Other Modifiers:
    - other_tools/index.md
    - other_tools/instance_object.md
    - other_tools/mark_sharp.md
    - other_tools/sharp_edges_to_attribute.md
    - other_tools/auto-flip_faces.md

  - Manual Tools:
    - manual_tools/index.md
    - manual_tools/recalculate_normals.md

  - Add-on:
    - add-on/index.md
    - add-on/boolean_pro.md